version: '3'

services:
  app:
    container_name: node-hapi-mongo
    restart: always #if fails, just restart
    build: ./node-hapi-mongo
    ports: 
      - '3000:3000'
    volumes:
      # - type: volume
      #     source: ./
      #     target: /usr/src
      - ./node-hapi-mongo:/usr/src/app
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'

  # nginx-app:
  #   container_name: nginx-react
  #   build: ./nginx-react
  #   ports:
  #     - '4000:4000'
  #   volumes:
  #     - ./nginx-react:/usr/src/nginx-app