version: '3'

services:
  app:
    container_name: node-hapi-mongo
    restart: always #if fails, just restart
    build: .
    ports: 
      - '3000:3000'
    volumes:
      # - type: volume
      #     source: ./
      #     target: /usr/src
      - .:/usr/src/app
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'